// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	log "github.com/aws/amazon-ssm-agent/agent/log"
	mock "github.com/stretchr/testify/mock"
)

// Detector is an autogenerated mock type for the Detector type
type Detector struct {
	mock.Mock
}

// GetName provides a mock function with given fields:
func (_m *Detector) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IsEc2 provides a mock function with given fields: _a0
func (_m *Detector) IsEc2(_a0 log.T) bool {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for IsEc2")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(log.T) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewDetector creates a new instance of Detector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDetector(t interface {
	mock.TestingT
	Cleanup(func())
}) *Detector {
	mock := &Detector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
