// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	log "github.com/aws/amazon-ssm-agent/agent/log"
	mock "github.com/stretchr/testify/mock"
)

// Ec2Detector is an autogenerated mock type for the Ec2Detector type
type Ec2Detector struct {
	mock.Mock
}

// IsEC2Instance provides a mock function with given fields: _a0
func (_m *Ec2Detector) IsEC2Instance(_a0 log.T) bool {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for IsEC2Instance")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(log.T) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewEc2Detector creates a new instance of Ec2Detector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEc2Detector(t interface {
	mock.TestingT
	Cleanup(func())
}) *Ec2Detector {
	mock := &Ec2Detector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
